version: "3"
services:
    main:
        image: c3vis
        ports:
          - "3000:3000"
        build:
            context: .
            dockerfile: Dockerfile
        container_name: c3vis
        env_file:
          - .env
